### ISSUE TITLE
Counter display bad value when i use multiple simplelightbox instances

### ISSUE THREAD

**Issue by raphaelriehl** [andreknieriem/simplelightbox#26]
Hello,

First of all, thank you for your application that is really good.
But i have a little bug with the counter.
When i click on next and previous arrows (if i have multiple instances of simplelightbox on the same page), the counter display a bad value (1/10 instead of 6/10, for example).

**Comment by andreknieriem** [comment]
Hi raphael. I will look whats the problem! thanks for your help

**Comment by Skinwalker** [comment]
Just move the simpleLightbox Setup inside a each() function

```
$('.js-gallery').each(function() {
    $(this).find('a').simpleLightbox();
});
```

That worked for me

**Comment by raphaelriehl** [comment]
Thanks for your answers.
@Skinwalker : But i have many instances with differents parent's containers and configurations.
If i have 30 pictures on my page, i want a counter for all groups of pictures (1/2, 1/15, 1/3, 1/10), but not an unique counter (1/30) for all pictures.
I hope you understand me, i'm french and i'm not good in english.

To explain my problem here's my code : 
`$('.slideshow-collection a').simpleLightbox();`
`$('.slideshow-webcams a').simpleLightbox();`
`$('#main article a.lightbox, .widget-type-text .widget-content a.lightbox').simpleLightbox({'nav': false, 'showCounter': false});`
I have 3 types of picture's groups.

**Comment by andreknieriem** [comment]
Hi raphael, your problem is the following line:

$('#main article a.lightbox, .widget-type-text .widget-content a.lightbox').simpleLightbox({'nav': false, 'showCounter': false});

Everything in the selector will be counted, so you got the number of all these galleries. Just call them standalone:

$('#main article a.lightbox).simpleLightbox({'nav': false, 'showCounter': false});

$('.widget-type-text .widget-content a.lightbox').simpleLightbox({'nav': false, 'showCounter': false});
