### ISSUE TITLE
Lightbox does not bind to duplicate element

### ISSUE THREAD

**Issue by AlexTies** [andreknieriem/simplelightbox#262]
Hello, it seems like simplelightbox is not initializing correctly when there are two identical items.
When trying to initialize SimpleLightbox with

```
const boxes = document.querySelectorAll('.lightbox');
const sL = new SimpleLightbox(boxes);
```

on this html
```
    <a class="lightbox" href="https://dummyimage.com/200/ffff00/000000">
      <img src="https://dummyimage.com/200/ffff00/000000" />
    </a>
    <a class="lightbox" href="https://dummyimage.com/200/ffff00/000000">
      <img src="https://dummyimage.com/200/ffff00/000000" />
    </a>
```

Only one of the two containers is bound. The second one is ignored. If i change the second container to a different image it once again works. The second console log is of sL.elements, the first one of const: boxes.

<img width="401" alt="Bildschirmfoto 2022-02-08 um 22 42 42" src="https://user-images.githubusercontent.com/4974876/153080573-0633dc24-f5c8-40b4-b3d1-85c751b5aff5.png">

**Comment by andreknieriem** [comment]
Hey. You are using it wrong. The lightbox itself gets all anchor tags. So you can just do 

`const sL = new SimpleLightbox('.lightbox', { });`

Additionally the link to the image is for both the same, so the option **uniqueImages** will filter one of them and the third point is the option **fileExt**, which will ignore all of them, because https://dummyimage.com/200/ffff00/000000 has no valid image file extension. You can bypass the check by just setting **fileExt: false**
