### ISSUE TITLE
HTML5 <figcaption> as Caption-Selector?

### ISSUE THREAD

**Issue by bastianandre** [andreknieriem/simplelightbox#62]
Hey Andre,

Thanks for your great work! I really enjoy using your lightbox plugin.
But is there a way to use the `<figcaption>` tag as source for the image caption?

Thank you for your response in advance!

**Comment by andreknieriem** [comment]
This should work with the option "captionSelector" = figcaption and "captionType" = text.

Best regards

**Comment by BastianA** [comment]
Thank you for your reply!
I hope I don't bother you, but unfortunately, your solution is not working for me – maybe because the "Caption Attribute" field is automatically filled with 'alt' or 'title' when left empty and saved (?).

MY HTML markup is as follows:
`<figure>`<br>&nbsp;&nbsp;&nbsp;`<a>`<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<img src=""  srcset="" alt ="">`<br>&nbsp;&nbsp;&nbsp;`</a>`<br>&nbsp;&nbsp;&nbsp;`<figcaption>`figcaption text`</figcaption>`<br>`<figure>`

**Comment by awplige** [comment]
# **https://github.com/awplige?tab=repositories**

## See Our New Repositories   

## 15+ Repositories   

### That Should Be Use Full For Your Sites.

### Thanks

**Comment by sashtown** [comment]
Hi @andreknieriem! Any news on this? Any example/docs? Can't get it to work.

**Comment by andreknieriem** [comment]
Will take a look.

**Comment by sashtown** [comment]
Hi @andreknieriem, guess I have to bother you again cause it still doesn't work, at least on my side. I'm getting a quite similar error in the console: 

`DOMException: Failed to execute 'querySelector' on 'Document': '[...] + figcaption' is not a valid selector.`

I can open the lightbox, the counter works as expected but I can't navigate through the gallery or even use the closing "x". Closing the lightbox only works with ESC. Would be very cool if you could have a look into this. Thanks!

**Comment by michaelmannucci** [comment]
> 

Did you figure this out? Getting the same error.

**Comment by michaelmannucci** [comment]
just FYI, latest version that works for me is 2.10.4

**Comment by andreknieriem** [comment]
Works now again
